### ISSUE TITLE
Feature request: Support Safari

### ISSUE THREAD

**Issue by zenangst** [onmyway133/github-extended#1]
It would be neat if you would supply a Safari extension for this library as well 😁

**Comment by RamonGilabert** [comment]
+1. What is this Chrome thing you talk about?

**Comment by zenangst** [comment]
@RamonGilabert No clue, must be a hipster thing. Kids nowadays... _feels old_

**Comment by onmyway133** [comment]
@RamonGilabert this is just a toggle to show more than 5 repositories
@zenangst thanks, I 'll consider Safari
